version: '3.7'

services:

  master_chief:

    build: ./webapp

    volumes:
      - ./webapp/react:/var/www/react
      - ./webapp/public:/var/www/public
      - /var/www/react/node_modules

    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      HOST:        ${HOST}
      PORT:        ${PORT}

    networks:
      - unsc_infinity

  cortana:

    image: nginx:latest

    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./webapp/public:/var/www/public

    ports:
      - "80:80"
      - "8080:8080"

    networks:
      - unsc_infinity

networks:
  unsc_infinity:
      driver: bridge
