version: '3.7'

services:
  master_chief:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/src
      - /var/www/src/node_modules
    ports:
      - "80:80"
